name: 功能请求
description: 向我们报告一个Bug以帮助我们改进MSL
title: "[Feat]: "
labels: ["功能请求enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        感谢您向我们提交功能请求！
  - type: checkboxes
    id: check
    attributes:
      label: 检查
      description: 警告:在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
      options:
        - label: 我确认我使用的是 [最新版本](https://files.mslmc.cn/MSL.exe) 的MSL.
          required: true
        - label: 我确认我提交的功能请求没有人提交过.
          required: true
        - label: 我认为这个功能是可以实现的，是对大部分人有用的.
          required: true
  - type: textarea
    id: feat
    attributes:
      label: 描述功能
      description: 请清晰地描述您想要的功能，并提供相关的信息。
      placeholder: 请清晰地描述您想要的功能，并提供相关的信息。
      value: "feature"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 实现方法
      description: 请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。