//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSL.langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSL.langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string _Done {
            get {
                return ResourceManager.GetString("_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string _OK {
            get {
                return ResourceManager.GetString("_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已关闭 的本地化字符串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收起 的本地化字符串。
        /// </summary>
        public static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载内网映射中…… 的本地化字符串。
        /// </summary>
        public static string Download_Frpc_Info {
            get {
                return ResourceManager.GetString("Download_Frpc_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校验完整性失败！请尝试重新下载！ 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_CheckIntegrityFailed {
            get {
                return ResourceManager.GetString("DownloadDialog_CheckIntegrityFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载取消！ 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_DownloadCancel {
            get {
                return ResourceManager.GetString("DownloadDialog_DownloadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载完成！ 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadDialog_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载失败！ 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadDialog_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已下载：{0}MB/{1}MB 进度：{2}% 速度：{3}MB/s 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_Downloading {
            get {
                return ResourceManager.GetString("DownloadDialog_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载中，进度{0}% 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_Mode2_Downloading {
            get {
                return ResourceManager.GetString("DownloadDialog_Mode2_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始下载……大小：{0}MB 的本地化字符串。
        /// </summary>
        public static string DownloadDialog_OnDownloadStarted {
            get {
                return ResourceManager.GetString("DownloadDialog_OnDownloadStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 展开 的本地化字符串。
        /// </summary>
        public static string Expand {
            get {
                return ResourceManager.GetString("Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开服 的本地化字符串。
        /// </summary>
        public static string Form_ServerRunner_Launch {
            get {
                return ResourceManager.GetString("Form_ServerRunner_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关服 的本地化字符串。
        /// </summary>
        public static string Form_ServerRunner_Stop {
            get {
                return ResourceManager.GetString("Form_ServerRunner_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        public static string InputDialog_Title {
            get {
                return ResourceManager.GetString("InputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中…… 的本地化字符串。
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中，请稍等…… 的本地化字符串。
        /// </summary>
        public static string Loading_PlzWait {
            get {
                return ResourceManager.GetString("Loading_PlzWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器、内网映射或联机功能正在运行中，关闭软件可能会让这些进程在后台一直运行并占用资源！确定要继续关闭吗？
        ///注：如果想隐藏主窗口的话，请前往设置打开托盘图标 的本地化字符串。
        /// </summary>
        public static string MainWindow_Close_Warning {
            get {
                return ResourceManager.GetString("MainWindow_Close_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器、内网映射或联机功能正在运行中，关闭软件可能会让这些进程在后台一直运行并占用资源！确定要继续关闭吗？ 的本地化字符串。
        /// </summary>
        public static string MainWindow_Close_Warning2 {
            get {
                return ResourceManager.GetString("MainWindow_Close_Warning2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在为你自动打开内网映射…… 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_AutoLaunchFrpc {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchFrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动内网映射失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_AutoLaunchFrpcErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchFrpcErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在为你自动打开相应服务器…… 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_AutoLaunchServer {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动服务器失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_AutoLaunchServerErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchServerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本高于正式版本，若使用中遇到BUG，请及时反馈！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_BeatVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_BeatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本高于最新正式版，若遇到Bug，请及时向开发者反馈！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_BetaVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_BetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_CheckUpdateErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_CheckUpdateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在加载配置文件时出现错误，此报错可能不影响软件运行，但还是建议您将其反馈给作者！
        ///错误代码： 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_ConfigErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ConfigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在加载配置文件时出现错误，将进行重试，若点击确定后软件突然闪退，请尝试使用管理员身份运行或将此问题报告给作者！
        ///错误代码： 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_ConfigErr2 {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ConfigErr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用本软件，即代表您已阅读并接受本软件的使用协议：https://www.mslmc.cn/eula.html 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_Eula {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在初始化加载过程中出现问题，请尝试用管理员身份运行MSL……
        ///错误代码： 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_InitErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_InitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件已是最新版本！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_LatestVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取系统内存失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_MemoryErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_MemoryErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接MSL服务器失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_MSLServerDown {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_MSLServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阅读协议 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_ReadEula {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ReadEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您拒绝了更新到新版本，若在此版本中遇到bug，请勿报告给作者！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_RefuseUpdate {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_RefuseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_Update {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，版本号为：{0}，是否进行更新？
        ///更新日志： 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_UpdateInfo {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器/内网映射/点对点联机正在运行中，若此时更新，会造成后台残留，请将前者关闭后再进行更新！ 的本地化字符串。
        /// </summary>
        public static string MainWindow_GrowlMsg_UpdateWarning {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Frpc {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Frpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Home {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_OnlinePlay {
            get {
                return ResourceManager.GetString("MainWindow_Menu_OnlinePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_ServerList {
            get {
                return ResourceManager.GetString("MainWindow_Menu_ServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Setting {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 好的 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已开启 的本地化字符串。
        /// </summary>
        public static string Opened {
            get {
                return ResourceManager.GetString("Opened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开网站 的本地化字符串。
        /// </summary>
        public static string OpenWebsite {
            get {
                return ResourceManager.GetString("OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于软件（{0}） 的本地化字符串。
        /// </summary>
        public static string Page_About_AboutMSL {
            get {
                return ResourceManager.GetString("Page_About_AboutMSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Server Launcher(MSL) Copyright © 2021-2025 By MSLTeam
        ///本软件与Microsoft、Mojang Studio(Mojang AB)无任何隶属关系
        ///本软件为开源软件，用户使用本软件从事的任何行为均与开发者无关
        ///本软件接入的第三方服务，其相关权利归第三方所有
        ///
        ///开服器的正常运行离不开下面的下载源/站点，特此感谢：
        ///CurseForge/Modrinth —— 模组、模组整合包下载源API
        ///BMCLAPI —— Forge服务端安装文件国内镜像源
        ///MSLAPI —— MSL自有服务端&amp;运行库镜像源
        ///以及其他服务端官方和第三方下载源……
        ///
        ///同时感谢所有使用MSL的用户，以及给MSL提出过改进建议和Bug的用户
        ///感谢各位的支持与信任！ 的本地化字符串。
        /// </summary>
        public static string Page_About_MainContent {
            get {
                return ResourceManager.GetString("Page_About_MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源（Github） 的本地化字符串。
        /// </summary>
        public static string Page_About_OpenSource {
            get {
                return ResourceManager.GetString("Page_About_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖/包 的本地化字符串。
        /// </summary>
        public static string Page_About_Package {
            get {
                return ResourceManager.GetString("Page_About_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赞助 的本地化字符串。
        /// </summary>
        public static string Page_About_Sponsor {
            get {
                return ResourceManager.GetString("Page_About_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件制作不易，您的支持就是我们的动力！ 的本地化字符串。
        /// </summary>
        public static string Page_About_SponsorText {
            get {
                return ResourceManager.GetString("Page_About_SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方网站/文档：https://www.mslmc.cn/ 的本地化字符串。
        /// </summary>
        public static string Page_About_Website {
            get {
                return ResourceManager.GetString("Page_About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭内网映射 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Close {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Copy {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接地址： 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Domain {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用此IP来连接： 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_IP {
            get {
                return ResourceManager.GetString("Page_FrpcPage_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 若上面地址无法连接，使用此IP： 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_IP2 {
            get {
                return ResourceManager.GetString("Page_FrpcPage_IP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_IPNull {
            get {
                return ResourceManager.GetString("Page_FrpcPage_IPNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动内网映射 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Launch {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测节点信息中…… 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_Checking {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChmlFrp节点 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_ChmlFrp {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_ChmlFrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义节点 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_CustomFrp {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_CustomFrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取Frp信息失败，建议重新配置！ 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_Failed {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测节点状态失败，若无法连接，请重新配置！ 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_Offline {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpenFrp节点 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_OpenFrp {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_OpenFrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟： 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_Ping {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口： 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Status_Port {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Status_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隧道列表（双击进入详情页） 的本地化字符串。
        /// </summary>
        public static string Page_FrpcPage_Title {
            get {
                return ResourceManager.GetString("Page_FrpcPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建一个新的服务器 的本地化字符串。
        /// </summary>
        public static string Page_Home_CreateServer {
            get {
                return ResourceManager.GetString("Page_Home_CreateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启服务器 的本地化字符串。
        /// </summary>
        public static string Page_Home_LaunchServer {
            get {
                return ResourceManager.GetString("Page_Home_LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        public static string Page_Home_Notice {
            get {
                return ResourceManager.GetString("Page_Home_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点对点联机 的本地化字符串。
        /// </summary>
        public static string Page_Home_P2PPlay {
            get {
                return ResourceManager.GetString("Page_Home_P2PPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        public static string Page_Home_Recommendations {
            get {
                return ResourceManager.GetString("Page_Home_Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：此功能尚不稳定，无法穿透所有类型的NAT，若联机失败，请尝试开服务器并使用内网映射联机！
        ///该功能可能需要正版账户，若无法联机，请从网络上寻找解决方法或尝试开服务器并使用内网映射联机！ 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Announce {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Announce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭房间 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_CloseRoom {
            get {
                return ResourceManager.GetString("Page_OnlinePage_CloseRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭成功！ 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_CloseSuc {
            get {
                return ResourceManager.GetString("Page_OnlinePage_CloseSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间密钥： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Create_key {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Create_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏端口： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Create_Port {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Create_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Create_RoomNo_ {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Create_RoomNo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击创建房间 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_CreateRoom {
            get {
                return ResourceManager.GetString("Page_OnlinePage_CreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桥接失败！ 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Err {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现错误，请检查是否有杀毒软件误杀并重试: 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_ErrMsg1 {
            get {
                return ResourceManager.GetString("Page_OnlinePage_ErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出房间 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_ExitRoom {
            get {
                return ResourceManager.GetString("Page_OnlinePage_ExitRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建房间——房主 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Header_Create {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Header_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入房间——成员 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Header_Join {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Header_Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间密钥： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Join_Key {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Join_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定端口（默认25565，非必要别改）： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Join_Port {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Join_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号： 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Join_RoomNo_ {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Join_RoomNo.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击加入房间 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_JoinRoom {
            get {
                return ResourceManager.GetString("Page_OnlinePage_JoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Log {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录服务器成功！ 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_LoginSuc {
            get {
                return ResourceManager.GetString("Page_OnlinePage_LoginSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：检测中 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_ServerStatusChecking {
            get {
                return ResourceManager.GetString("Page_OnlinePage_ServerStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：检测超时，服务器可能下线 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_ServerStatusDown {
            get {
                return ResourceManager.GetString("Page_OnlinePage_ServerStatusDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：可用 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_ServerStatusOK {
            get {
                return ResourceManager.GetString("Page_OnlinePage_ServerStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桥接成功！ 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Suc {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点对点联机 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_Title {
            get {
                return ResourceManager.GetString("Page_OnlinePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机教程 的本地化字符串。
        /// </summary>
        public static string Page_OnlinePage_UseTip {
            get {
                return ResourceManager.GetString("Page_OnlinePage_UseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选服务器 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Delete {
            get {
                return ResourceManager.GetString("Page_ServerList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开服器检测到配置文件出现了错误，是第一次使用吗？
        ///是否创建一个新的服务器？ 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Dialog_NoConfTip {
            get {
                return ResourceManager.GetString("Page_ServerList_Dialog_NoConfTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Do {
            get {
                return ResourceManager.GetString("Page_ServerList_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启服务器 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_LaunchServer {
            get {
                return ResourceManager.GetString("Page_ServerList_LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理服务器模组/插件 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_ManageModsOrPlugins {
            get {
                return ResourceManager.GetString("Page_ServerList_ManageModsOrPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开服务器文件夹 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_OpenDir {
            get {
                return ResourceManager.GetString("Page_ServerList_OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Refresh {
            get {
                return ResourceManager.GetString("Page_ServerList_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名称 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_ServerName {
            get {
                return ResourceManager.GetString("Page_ServerList_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改服务器设置 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Setting {
            get {
                return ResourceManager.GetString("Page_ServerList_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Status {
            get {
                return ResourceManager.GetString("Page_ServerList_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器列表 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_Title {
            get {
                return ResourceManager.GetString("Page_ServerList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令行开服 的本地化字符串。
        /// </summary>
        public static string Page_ServerList_UseCMDLaunch {
            get {
                return ResourceManager.GetString("Page_ServerList_UseCMDLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入需要自启动Frpc的ID（ID在方括号内，使用半角逗号分隔和结尾）： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_ALF_FrpcList {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_ALF_FrpcList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动列表： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_ALS_AutoLaunchServers {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_ALS_AutoLaunchServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器列表： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_ALS_ServerList {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_ALS_ServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录玩家功能 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_ARASL_RecordPlayers {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_ARASL_RecordPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示占用功能 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_ARASL_ShowSysOccupation {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_ARASL_ShowSysOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动软件时自动运行Frpc隧道 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_AutoLaunchFrpc {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_AutoLaunchFrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动软件时自动运行服务器 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_AutoLaunchServer {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_AutoLaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开服时自动开启 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_AutoRunAtServerLaunched {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_AutoRunAtServerLaunched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开机自动启动MSL： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_AutoRunAtStartup {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_AutoRunAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遇到更新时自动更新MSL： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_AS_AutoUpdate {
            get {
                return ResourceManager.GetString("Page_SettingsPage_AS_AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动化选项 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_Card_AutomationSettings {
            get {
                return ResourceManager.GetString("Page_SettingsPage_Card_AutomationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能调整 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_Card_ChangeFunctions {
            get {
                return ResourceManager.GetString("Page_SettingsPage_Card_ChangeFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备信息 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_Card_DeviceInfo {
            get {
                return ResourceManager.GetString("Page_SettingsPage_Card_DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮肤选项 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_Card_SkinSettings {
            get {
                return ResourceManager.GetString("Page_SettingsPage_Card_SkinSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加下载任务： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_AddDownloadTask {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_AddDownloadTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础功能： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BasicFunction {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BasicFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BF_CheckUpdate {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BF_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL提示： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BF_MSLTips {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BF_MSLTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘图标： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BF_NotifyIcon {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BF_NotifyIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复默认设置 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BF_RecoveryBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BF_RecoveryBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件文档 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_BF_SoftwareWiki {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_BF_SoftwareWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载线程（默认为4，建议不超过16）： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_DownloadThread {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_DownloadThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言（Language）： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_Language {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开任务列表 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_CF_OpenTaskManager {
            get {
                return ResourceManager.GetString("Page_SettingsPage_CF_OpenTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制设备ID 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_DI_CopyDID {
            get {
                return ResourceManager.GetString("Page_SettingsPage_DI_CopyDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备ID： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_DI_DeviceID {
            get {
                return ResourceManager.GetString("Page_SettingsPage_DI_DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备ID是MSL开发团队追踪MSL发生意外错误的重要依据，需要时请提供给我们！ 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_DI_Tips1 {
            get {
                return ResourceManager.GetString("Page_SettingsPage_DI_Tips1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每台设备的设备ID是唯一的（仅当重装系统/切换用户会变化） 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_DI_Tips2 {
            get {
                return ResourceManager.GetString("Page_SettingsPage_DI_Tips2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 背景图片： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_BackgroundImg {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_BackgroundImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改背景图片 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_BI_ChangeBackImg {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_BI_ChangeBackImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除背景图片 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_BI_DelBackImg {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_BI_DelBackImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 蓝色皮肤（默认） 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_BlueSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_BlueSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暗色模式 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_DarkTheme {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿色皮肤 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_GreenSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_GreenSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 橙色皮肤 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_OrangeSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_OrangeSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粉色皮肤 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_PinkSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_PinkSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紫色皮肤 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_PurpleSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_PurpleSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红色皮肤 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_RedSkinBtn {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_RedSkinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半透明标题栏 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_SemitransparentTitle {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_SemitransparentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题颜色： 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_ThemeColor {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_ThemeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用系统样式 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_UseSysTheme {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_UseSysTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 千万别点！ 的本地化字符串。
        /// </summary>
        public static string Page_SettingsPage_SS_WesternEgg {
            get {
                return ResourceManager.GetString("Page_SettingsPage_SS_WesternEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Tip {
            get {
                return ResourceManager.GetString("Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新内网映射中…… 的本地化字符串。
        /// </summary>
        public static string Update_Frpc_Info {
            get {
                return ResourceManager.GetString("Update_Frpc_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
