//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSL.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSL.i18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 您使用的开服器已是最新版本！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_LatestVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Frpc {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Frpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Home {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_OnlinePlay {
            get {
                return ResourceManager.GetString("MainWindow_Menu_OnlinePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_ServerList {
            get {
                return ResourceManager.GetString("MainWindow_Menu_ServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Setting {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启服务器 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_LaunchServer {
            get {
                return ResourceManager.GetString("Pages_Home_LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告： 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_Notice {
            get {
                return ResourceManager.GetString("Pages_Home_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点对点联机 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_P2PPlay {
            get {
                return ResourceManager.GetString("Pages_Home_P2PPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为您推荐： 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_Recommendations {
            get {
                return ResourceManager.GetString("Pages_Home_Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：此功能目前不稳定，无法穿透所有类型的NAT，若联机失败，请尝试开服务器并使用内网映射联机！\n该功能可能需要正版账户，若无法联机，请从网络上寻找解决方法或尝试开服务器并使用内网映射联机！ 的本地化字符串。
        /// </summary>
        internal static string Pages_OnlinePage_Dialog_Tips {
            get {
                return ResourceManager.GetString("Pages_OnlinePage_Dialog_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Do {
            get {
                return ResourceManager.GetString("Pages_ServerList_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名称 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_ServerName {
            get {
                return ResourceManager.GetString("Pages_ServerList_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Status {
            get {
                return ResourceManager.GetString("Pages_ServerList_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器列表（双击可快捷启动服务器）： 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Title {
            get {
                return ResourceManager.GetString("Pages_ServerList_Title", resourceCulture);
            }
        }
    }
}
