//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSL.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSL.i18n.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Dialog_Done {
            get {
                return ResourceManager.GetString("Dialog_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Dialog_Err {
            get {
                return ResourceManager.GetString("Dialog_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Dialog_Tip {
            get {
                return ResourceManager.GetString("Dialog_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string Dialog_Warning {
            get {
                return ResourceManager.GetString("Dialog_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在为你自动打开内网映射…… 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_AutoLaunchFrpc {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchFrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动内网映射失败！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_AutoLaunchFrpcErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchFrpcErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在为你自动打开相应服务器…… 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_AutoLaunchServer {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动启动服务器失败！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_AutoLaunchServerErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_AutoLaunchServerErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本高于正式版本，若使用中遇到BUG，请及时反馈！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_BeatVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_BeatVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本高于最新正式版，若遇到Bug，请及时向开发者反馈！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_BetaVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_BetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查更新失败！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_CheckUpdateErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_CheckUpdateErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器、内网映射或联机功能正在运行中，关闭软件可能会让这些进程在后台一直运行并占用资源！确定要继续关闭吗？
        ///注：如果想隐藏主窗口的话，请前往设置打开托盘图标 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_Close {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器、内网映射或联机功能正在运行中，关闭软件可能会让这些进程在后台一直运行并占用资源！确定要继续关闭吗？ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_Close2 {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Close2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在加载配置文件时出现错误，此报错可能不影响软件运行，但还是建议您将其反馈给作者！
        ///错误代码： 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_ConfigErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ConfigErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在加载配置文件时出现错误，将进行重试，若点击确定后软件突然闪退，请尝试使用管理员身份运行或将此问题报告给作者！
        ///错误代码： 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_ConfigErr2 {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ConfigErr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用本软件，即代表您已阅读并接受本软件的使用协议：https://www.mslmc.cn/eula.html
        ///如果您不接受，请立即退出本软件并删除相关文件！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_Eula {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Eula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MSL在初始化加载过程中出现问题，请尝试用管理员身份运行MSL……
        ///错误代码： 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_InitErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_InitErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件已是最新版本！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_LatestVersion {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取系统内存失败！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_MemoryErr {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_MemoryErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件主服务器连接超时，已切换至备用服务器！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_MSLServerDown {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_MSLServerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阅读协议 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_ReadEula {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_ReadEula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您拒绝了更新到新版本，若在此版本中遇到bug，请勿报告给作者！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_RefuseUpdate {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_RefuseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_Update {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_UpdateFailed {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发现新版本，版本号为： 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_UpdateInfo1 {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ，是否进行更新？
        ///更新日志：
        /// 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_UpdateInfo2 {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器/内网映射/点对点联机正在运行中，若此时更新，会造成后台残留，请将前者关闭后再进行更新！ 的本地化字符串。
        /// </summary>
        internal static string MainWindow_GrowlMsg_UpdateWarning {
            get {
                return ResourceManager.GetString("MainWindow_GrowlMsg_UpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_About {
            get {
                return ResourceManager.GetString("MainWindow_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 映射 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Frpc {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Frpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主页 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Home {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_OnlinePlay {
            get {
                return ResourceManager.GetString("MainWindow_Menu_OnlinePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_ServerList {
            get {
                return ResourceManager.GetString("MainWindow_Menu_ServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string MainWindow_Menu_Setting {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于软件 的本地化字符串。
        /// </summary>
        internal static string Pages_About_AboutMSL {
            get {
                return ResourceManager.GetString("Pages_About_AboutMSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minecraft Server Launcher(MSL) Copyright © 2021-2024 By MSLTeam
        ///本软件与Microsoft、Mojang Studio(Mojang AB)无任何隶属关系
        ///本软件为开源软件，用户使用本软件从事的任何行为均与开发者无关
        ///本软件接入的第三方服务，其相关权利归第三方所有
        ///
        ///开服器的正常运行离不开下面的下载源/站点，特此感谢：
        ///CurseForge —— 模组、模组整合包下载源API
        ///BMCLAPI —— Forge服务端下载源
        ///以及其他服务端官方和第三方下载源……
        ///
        ///同时感谢所有使用MSL的用户，以及给MSL提出过改进建议和Bug的用户
        ///感谢各位的支持与信任！ 的本地化字符串。
        /// </summary>
        internal static string Pages_About_MainContent {
            get {
                return ResourceManager.GetString("Pages_About_MainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开源（Github） 的本地化字符串。
        /// </summary>
        internal static string Pages_About_OpenSource {
            get {
                return ResourceManager.GetString("Pages_About_OpenSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开网站 的本地化字符串。
        /// </summary>
        internal static string Pages_About_OpenWebsite {
            get {
                return ResourceManager.GetString("Pages_About_OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 依赖/包 的本地化字符串。
        /// </summary>
        internal static string Pages_About_Package {
            get {
                return ResourceManager.GetString("Pages_About_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赞助 的本地化字符串。
        /// </summary>
        internal static string Pages_About_Sponsor {
            get {
                return ResourceManager.GetString("Pages_About_Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件制作不易，您的支持就是我们的动力！ 的本地化字符串。
        /// </summary>
        internal static string Pages_About_SponsorText {
            get {
                return ResourceManager.GetString("Pages_About_SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方网站/文档：https://www.mslmc.cn/ 的本地化字符串。
        /// </summary>
        internal static string Pages_About_Website {
            get {
                return ResourceManager.GetString("Pages_About_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭内网映射 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_Close {
            get {
                return ResourceManager.GetString("Pages_Frpc_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_Copy {
            get {
                return ResourceManager.GetString("Pages_Frpc_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用此IP来连接： 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_IP {
            get {
                return ResourceManager.GetString("Pages_Frpc_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_IPNull {
            get {
                return ResourceManager.GetString("Pages_Frpc_IPNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动内网映射 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_Launch {
            get {
                return ResourceManager.GetString("Pages_Frpc_Launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 状态 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_Status {
            get {
                return ResourceManager.GetString("Pages_Frpc_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内网映射列表（双击进入详情页） 的本地化字符串。
        /// </summary>
        internal static string Pages_Frpc_Title {
            get {
                return ResourceManager.GetString("Pages_Frpc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建一个新的服务器 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_CreateServer {
            get {
                return ResourceManager.GetString("Pages_Home_CreateServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启服务器 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_LaunchServer {
            get {
                return ResourceManager.GetString("Pages_Home_LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公告 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_Notice {
            get {
                return ResourceManager.GetString("Pages_Home_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点对点联机 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_P2PPlay {
            get {
                return ResourceManager.GetString("Pages_Home_P2PPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        internal static string Pages_Home_Recommendations {
            get {
                return ResourceManager.GetString("Pages_Home_Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭房间 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Close {
            get {
                return ResourceManager.GetString("Pages_Online_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭成功！ 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_CloseSuc {
            get {
                return ResourceManager.GetString("Pages_Online_CloseSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间密钥： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Create_key {
            get {
                return ResourceManager.GetString("Pages_Online_Create_key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏端口： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Create_Port {
            get {
                return ResourceManager.GetString("Pages_Online_Create_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QQ号： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Create_QQn {
            get {
                return ResourceManager.GetString("Pages_Online_Create_QQn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击创建房间 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_CreateBtn {
            get {
                return ResourceManager.GetString("Pages_Online_CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载内网映射中··· 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_DlFrpc {
            get {
                return ResourceManager.GetString("Pages_Online_DlFrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间密钥： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Enter_Key {
            get {
                return ResourceManager.GetString("Pages_Online_Enter_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定端口（默认25565，非必要别改）： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Enter_Port {
            get {
                return ResourceManager.GetString("Pages_Online_Enter_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房主QQ号： 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Enter_QQn {
            get {
                return ResourceManager.GetString("Pages_Online_Enter_QQn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击加入房间 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_EnterBtn {
            get {
                return ResourceManager.GetString("Pages_Online_EnterBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桥接失败！ 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Err {
            get {
                return ResourceManager.GetString("Pages_Online_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现错误，请检查是否有杀毒软件误杀并重试: 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_ErrMsg1 {
            get {
                return ResourceManager.GetString("Pages_Online_ErrMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出房间 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_ExitRoom {
            get {
                return ResourceManager.GetString("Pages_Online_ExitRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入房间——成员 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Header_Enter {
            get {
                return ResourceManager.GetString("Pages_Online_Header_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建房间——房主 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_HeaderCreate {
            get {
                return ResourceManager.GetString("Pages_Online_HeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Log {
            get {
                return ResourceManager.GetString("Pages_Online_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录服务器成功！ 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_LoginSuc {
            get {
                return ResourceManager.GetString("Pages_Online_LoginSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：检测中 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_ServerStatusChecking {
            get {
                return ResourceManager.GetString("Pages_Online_ServerStatusChecking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：检测超时，服务器可能下线 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_ServerStatusDown {
            get {
                return ResourceManager.GetString("Pages_Online_ServerStatusDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态：可用 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_ServerStatusOK {
            get {
                return ResourceManager.GetString("Pages_Online_ServerStatusOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 桥接成功！ 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Suc {
            get {
                return ResourceManager.GetString("Pages_Online_Suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联机教程 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Tips1 {
            get {
                return ResourceManager.GetString("Pages_Online_Tips1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击打开网站 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_TipsOpenWeb {
            get {
                return ResourceManager.GetString("Pages_Online_TipsOpenWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点对点联机 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_Title {
            get {
                return ResourceManager.GetString("Pages_Online_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新内网映射中··· 的本地化字符串。
        /// </summary>
        internal static string Pages_Online_UdFrpc {
            get {
                return ResourceManager.GetString("Pages_Online_UdFrpc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意：此功能目前不稳定，无法穿透所有类型的NAT，若联机失败，请尝试开服务器并使用内网映射联机！
        ///该功能可能需要正版账户，若无法联机，请从网络上寻找解决方法或尝试开服务器并使用内网映射联机！ 的本地化字符串。
        /// </summary>
        internal static string Pages_OnlinePage_Dialog_Tips {
            get {
                return ResourceManager.GetString("Pages_OnlinePage_Dialog_Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选服务器 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Delete {
            get {
                return ResourceManager.GetString("Pages_ServerList_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开服器检测到配置文件出现了错误，是第一次使用吗？
        ///是否创建一个新的服务器？ 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Dialog_FirstUse {
            get {
                return ResourceManager.GetString("Pages_ServerList_Dialog_FirstUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Do {
            get {
                return ResourceManager.GetString("Pages_ServerList_Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启服务器 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_LaunchServer {
            get {
                return ResourceManager.GetString("Pages_ServerList_LaunchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理服务器模组/插件 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_ManageModsOrPlugins {
            get {
                return ResourceManager.GetString("Pages_ServerList_ManageModsOrPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开服务器文件夹 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_OpenDir {
            get {
                return ResourceManager.GetString("Pages_ServerList_OpenDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Refresh {
            get {
                return ResourceManager.GetString("Pages_ServerList_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器名称 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_ServerName {
            get {
                return ResourceManager.GetString("Pages_ServerList_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改服务器设置 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Setting {
            get {
                return ResourceManager.GetString("Pages_ServerList_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器状态 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Status {
            get {
                return ResourceManager.GetString("Pages_ServerList_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器列表（双击可快捷启动服务器） 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_Title {
            get {
                return ResourceManager.GetString("Pages_ServerList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令行开服 的本地化字符串。
        /// </summary>
        internal static string Pages_ServerList_UseCMDLaunch {
            get {
                return ResourceManager.GetString("Pages_ServerList_UseCMDLaunch", resourceCulture);
            }
        }
    }
}
