name: .NET Framework CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # 检出子模块

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore dependencies
      run: msbuild -t:restore

    - name: Build
      run: msbuild /p:Configuration=Release /p:Platform="x64"

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: MSL
        path: MSL/bin/x64/Release/MSL.exe
